# Generated by Django 3.0.7 on 2020-08-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadena', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrado',
            name='actualizado',
        ),
        migrations.RemoveField(
            model_name='registrado',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='registrado',
            name='edad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrado',
            name='media',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrado',
            name='nombre',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
