# Generated by Django 3.0.7 on 2020-08-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadena', '0002_auto_20200806_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrado',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
    ]
